name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build-Euler
      run: cargo build --bin ode_euler --verbose
    - name: Build-Heat
      run: cargo build --bin heat_eq --verbose
    - name: Run tests
      run: cargo test --verbose
